create table
  public.movies (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name text not null default ''::text,
    genres text null,
    average_rating bigint null,
    budget bigint null,
    box_office bigint null,
    demographic text null,
    release_date timestamp with time zone null,
    constraint movies_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.ratings (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    movie_id bigint null,
    user_id bigint null,
    rating bigint null,
    constraint ratings_pkey primary key (id),
    constraint unique_user_id_movie_id_rating unique (user_id, movie_id)
  ) tablespace pg_default;

create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    is_admin boolean not null default false,
    username text not null,
    constraint users_pkey primary key (id, created_at),
    constraint users_username_key unique (username)
  ) tablespace pg_default;


create table
  public.watched_movies (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    user_id bigint null,
    movie_id bigint null,
    constraint watched_movie_pkey primary key (id),
    constraint unique_user_id_movie_id unique (user_id, movie_id)
  ) tablespace pg_default;

/*
Data Used For v1_manual_testing
*/

INSERT INTO users (username) VALUES ('Rakesh');

INSERT INTO movies (name, genres, average_rating, budget, demographic, box_office, release_date ) VALUES ('Toy Story', ARRAY['Animation', 'Comedy', 'Family'], 0, 30000000, ARRAY[]::text[], 373554033, '1995-10-30 00:00:00+00');
INSERT INTO movies (name, genres, average_rating, budget, demographic, box_office, release_date ) VALUES ('Jumanji', ARRAY['Adventure', 'Fantasy', 'Family'], 0, 65000000, ARRAY[]::text[], 262797249, '1995-12-15 00:00:00+00');
INSERT INTO movies (name, genres, average_rating, budget, demographic, box_office, release_date ) VALUES ('Grumpier Old Men', ARRAY['Romance', 'Comedy'], 0, 0, ARRAY[]::text[], 0, '1995-12-22 00:00:00+00');
INSERT INTO movies (name, genres, average_rating, budget, demographic, box_office, release_date ) VALUES ('Waiting to Exhale', ARRAY['Comedy', 'Drama', 'Romance'], 0, 16000000, ARRAY[]::text[], 81452156, '1995-12-22 00:00:00+00');
INSERT INTO movies (name, genres, average_rating, budget, demographic, box_office, release_date ) VALUES ('Father of the Bride Part II', ARRAY['Comedy'], 0, 0, ARRAY[]::text[], 76578911, '1995-02-10 00:00:00+00');

INSERT INTO watched_movies (user_id, movie_id) VALUES (23, 1);
INSERT INTO watched_movies (user_id, movie_id) VALUES (23, 2);
INSERT INTO watched_movies (user_id, movie_id) VALUES (23, 5);

  

