path = r"/Users/taran/Desktop/movie_data/movies_metadata.csv"
write_path = r"/Users/taran/CSC365/365MM-/populate_data/data.csv"
movie_path = r"/Users/taran/CSC365/365MM-/populate_data/movie.csv"
genre_path = r"/Users/taran/CSC365/365MM-/populate_data/genre.csv"
language_path = r"/Users/taran/CSC365/365MM-/populate_data/language.csv"